Algoritmo "LerLivro"
Var
// Seção de Declarações das variáveis
nome : caracter
idade : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Escolher o livro")
Escreval("Ir em um lugar quieto")
Escreval("Abrir o livro")
Escreval("Ler o livro")
Escreval("Fechar o livro")

Escreval("Escreva seu nome: ")
Leia(nome)
Escreval("Seu nome é: ", nome)

Escreval("Coloque sua idade: ")
Leia(idade)
Escreval("Sua idade é: ", idade)

Fimalgoritmo